Creating a deployments-directory
at the very beginning of the challenge "yarn deploy" throws an error, the following error is solved by adding the missing directory:

Error: ENOENT: no such file or directory, scandir '/home/phil/ETH_speedrun/4_dex/packages/hardhat/deployments'
    at Object.readdirSync (node:fs:1413:3)
    at Object.loadAllDeployments (/home/phil/ETH_speedrun/4_dex/packages/hardhat/node_modules/hardhat-deploy/src/utils.ts:92:6)
    at DeploymentsManager.export (/home/phil/ETH_speedrun/4_dex/packages/hardhat/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1128:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
    at DeploymentsManager.runDeploy (/home/phil/ETH_speedrun/4_dex/packages/hardhat/node_modules/hardhat-deploy/src/DeploymentsManager.ts:893:5)
    at Environment._runTaskDefinition (/home/phil/ETH_speedrun/4_dex/packages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/home/phil/ETH_speedrun/4_dex/packages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/phil/ETH_speedrun/4_dex/packages/hardhat/deployments'
}
error Command failed with exit code 1.